language: rust
rust:
  - nightly
matrix:
  fast_finish: true
dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.12.1-xenial'
    packages:
      - mesa-common-dev
      - qt512declarative
      - qt512quickcontrols2
      - qt512graphicaleffects
install:
  - source /opt/qt512/bin/qt512-env.sh
after_success:
  - cargo build --release
  - cd linuxdeployqt.AppDir
  - cp ../target/release/biying .
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - ./linuxdeployqt-continuous-x86_64.AppImage biying.desktop -appimage -no-translations -no-copy-copyright-files -verbose=2 -qmldir=../assets
  - curl --upload-file *.AppImage https://transfer.sh/biying-git.$(git rev-parse --short HEAD)-x86_64.AppImage
