language: rust
rust:
  - nightly
matrix:
  fast_finish: true
dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.12.1-xenial'
    packages:
      - qt512declarative
install:
  - source /opt/qt512/bin/qt512-env.sh
