language: rust
rust:
  - nightly
matrix:
  fast_finish: true
dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.12.1-xenial'
      - sourceline: 'ppa:papirus/papirus'
    packages:
      - mesa-common-dev
      - qt512declarative
      - qt512quickcontrols2
      - qt512graphicaleffects
      - qt512svg
      - qt512tools
      # Qt plugins
      - fcitx-frontend-qt5
      - qt5-style-plugins
      - qt5-style-kvantum
install:
  - source /opt/qt512/bin/qt512-env.sh
before_script:
  - lrelease assets/i18n/*.ts
before_deploy:
  - cargo build --release
  - cd linuxdeployqt.AppDir
  - cp ../target/release/biying .
  - cp ../assets/livewallpaper.svg .
  - sudo cp -vnpr /usr/lib/x86_64-linux-gnu/qt5/plugins/* $QTDIR/plugins/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod +x ./linuxdeployqt-continuous-x86_64.AppImage
  - export VERSION=`git describe --tags`
  - ./linuxdeployqt-continuous-x86_64.AppImage biying.desktop -appimage -no-translations -no-copy-copyright-files -verbose=2 -qmldir=../assets -extra-plugins=styles/libkvantum.so
  - export FILE=`ls -t *.AppImage | head -1`
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$FILE"
  skip_cleanup: true
  on:
    tags: true
