name: CI

on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04]
        rust: [nightly]
        # include:
        # Allow failures on nightly
        # - rust: nightly
        #   can-fail: true
    runs-on: ${{ matrix.os }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Install dependencies
      shell: bash
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.1-xenial
        sudo apt-get update -y
        sudo apt-get install -y libdbus-1-dev \
        mesa-common-dev \
        qt512declarative
    - name: Run tests
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        cargo test --verbose
      # continue-on-error: ${{ matrix.can-fail }}
